// <auto-generated />
using System;
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dal.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20210803120747_BaseModel")]
    partial class BaseModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainModel.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Corridor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ClassroomId");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("DomainModel.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("DomainModel.Student", b =>
                {
                    b.HasBaseType("DomainModel.Person");

                    b.Property<double>("Average")
                        .HasColumnType("float");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClassDelegate")
                        .HasColumnType("bit");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DomainModel.Teacher", b =>
                {
                    b.HasBaseType("DomainModel.Person");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("HiringDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("ClassroomId")
                        .IsUnique()
                        .HasFilter("[ClassroomId] IS NOT NULL");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("DomainModel.Student", b =>
                {
                    b.HasOne("DomainModel.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassroomId");

                    b.HasOne("DomainModel.Person", null)
                        .WithOne()
                        .HasForeignKey("DomainModel.Student", "PersonId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("DomainModel.Teacher", b =>
                {
                    b.HasOne("DomainModel.Classroom", "Classroom")
                        .WithOne("Teacher")
                        .HasForeignKey("DomainModel.Teacher", "ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainModel.Person", null)
                        .WithOne()
                        .HasForeignKey("DomainModel.Teacher", "PersonId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("DomainModel.Classroom", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
